### ISSUE TITLE
Case-insensitive query generation

### ISSUE THREAD

**Issue by kirill-zaitsev** [nossrannug/feast-postgres#10]
I try to retrieve historical features from a Postgres batch source, using SQL as an entity_df parameter for get_historical_features.
Some of the column names have capital letters: EmployeeID, Date, etc.
```
    features = store.get_historical_features(
        features=feature_service,
        entity_df='select history."EmployeeID" as "EmployeeID", DATE(history."Date") as event_timestamp from public.history',
    ).to_df()
```
Usage of double quotes helps in vanilla PSQL, but in this case, the final join query is generated from a Jinja template that makes all columns lowercase. So, I receive errors such as this one:
```
  File "/home/k/venv/lib/python3.8/site-packages/feast_postgres/offline_stores/postgres.py", line 207, in _to_arrow_internal
    cur.execute(query)
psycopg2.errors.UndefinedColumn: column "employeeid" does not exist
LINE 13:                     CAST(EmployeeID as VARCHAR) ||
                                  ^
HINT:  Perhaps you meant to reference the column "sub.EmployeeID".
```
Seems to be a bug.

**Comment by nossrannug** [comment]
Hey @kirill-zaitsev, thanks for creating the issue.
I'll try to get this fixed over the weekend.

**Comment by nossrannug** [comment]
Quick and dirty. v0.2.3 should fix this issue.

**Comment by GirishShanmugam** [comment]
@nossrannug I am using v0.2.4 and still get this error when I have uppercase characters in my feature name(column name). I am using feast v0.16.0
```
File "/opt/venv/lib/python3.9/site-packages/feast_postgres/offline_stores/postgres.py", line 214, in _to_arrow_internal
    cur.execute(query)

psycopg2.errors.UndefinedColumn: column a.testColumn does not exist


LINE 6:                 SELECT a."test_case_id", a."testColumn", a."d...
                                                 ^
HINT:  Perhaps you meant to reference the column "a.testcolumn".
```
